[package]
name = "circuits"
type = "bin"
authors = [""]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-nr/", tag = "v3.0.0-devnet.6-patch.1", directory = "aztec" }
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }
uint_note = { path = "../uint-note" }
