  settled_note_hash: "0x109ebaffd4e6aa4e4c305606addd352dd432d37fd5541b67e86e7310cdf80053"
  contract_address: "0x0f140443f51fe2a1b9ca04b279cda12e2bbdd073efb6b09aed79a6a4315957d0"
  recipient: "0x116586dbcc81434e8b0727cbe282be01271886275e347489947af5d1b94618a4"
  randomness: "0x0000000000000000000000000000000000000000000000000000000000001b39",
  value: 69,
  storage_slot: "0x134f661dca40dad62341c230269bbed01da64b506e8a0e6e0a452a9262023012"
  note_nonce: "0x0fe225cdf1421a3266faf50f46025b73bb57858d10f7cd62875b47e988c64edd"