[package]
name = "uint_note"
authors = ["aztec-labs"]
compiler_version = ">=1.0.0"
type = "lib"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-nr/", tag = "v3.0.0-devnet.6-patch.1", directory = "aztec" }
