[package]
name = "uint_note"
authors = ["aztec-labs"]
compiler_version = ">=1.0.0"
type = "lib"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v3.0.0-devnet.20251212", directory = "noir-projects/aztec-nr/aztec" }
