[package]
name = "getting_started_contract"
authors = [""]
compiler_version = ">=1.0.0"
type = "contract"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v3.0.0-devnet.20251212", directory = "noir-projects/aztec-nr/aztec" }
# Local uint_note with create_note_with_randomness for hash verification demo
uint_note = { path = "../uint-note" }
