[package]
name = "custom_account"
authors = [""]
compiler_version = ">=1.0.0"
type = "contract"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v3.0.0-nightly.20251107", directory = "noir-projects/aztec-nr/aztec" }
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }
